2023-09-24 19:10:28,812 [main.py         | 51] INFO: Start to run instance_1
2023-09-24 19:10:28,812 [simulate_api.py | 60] INFO: Start time of the simulator: 2023-09-24 00:00:00, time interval:  600.00
2023-09-24 19:10:28,816 [input_utils.py  | 48] INFO: Get 154 factories
2023-09-24 19:10:29,302 [input_utils.py  | 52] INFO: Get 23562 routes
2023-09-24 19:10:29,313 [input_utils.py  | 57] INFO: Get 5 vehicles
2023-09-24 19:10:29,316 [input_utils.py  | 61] INFO: Get 50 orders
2023-09-24 19:10:29,316 [simulate_api.py | 87] INFO: Initial position of V_1 is e2d5093fbe36431f8986ddb0e1c586be
2023-09-24 19:10:29,316 [simulate_api.py | 87] INFO: Initial position of V_2 is 7fe14b93f0f04ee7a994ef5b2c1fdb72
2023-09-24 19:10:29,316 [simulate_api.py | 87] INFO: Initial position of V_3 is fa366fc87a124d32926daa5bb093129f
2023-09-24 19:10:29,316 [simulate_api.py | 87] INFO: Initial position of V_4 is e47399648fa842b2b8f80094343d8091
2023-09-24 19:10:29,316 [simulate_api.py | 87] INFO: Initial position of V_5 is becb4f85393540b287e7329758b8d832
2023-09-24 19:10:29,316 [main.py         | 85] ERROR: Failed to run simulator
2023-09-24 19:10:29,317 [main.py         | 86] ERROR: Error: 'NoneType' object has no attribute 'sar_sequence', Traceback (most recent call last):
  File "/Users/wangqianlong/Desktop/personal/github/xingtian/simulator/dpdp_competition/main.py", line 56, in <module>
    score = simulate(Configs.factory_info_file, Configs.route_info_file, instance)
  File "/Users/wangqianlong/Desktop/personal/github/xingtian/simulator/dpdp_competition/src/simulator/simulate_api.py", line 94, in simulate
    simulate_env.run()
  File "/Users/wangqianlong/Desktop/personal/github/xingtian/simulator/dpdp_competition/src/simulator/simulate_environment.py", line 96, in run
    agent.sar_sequence = []
AttributeError: 'NoneType' object has no attribute 'sar_sequence'

