2023-09-24 19:03:31,797 [main.py         | 51] INFO: Start to run instance_2
2023-09-24 19:03:31,798 [simulate_api.py | 60] INFO: Start time of the simulator: 2023-09-24 00:00:00, time interval:  600.00
2023-09-24 19:03:31,802 [input_utils.py  | 48] INFO: Get 154 factories
2023-09-24 19:03:32,809 [input_utils.py  | 52] INFO: Get 23562 routes
2023-09-24 19:03:32,825 [input_utils.py  | 57] INFO: Get 5 vehicles
2023-09-24 19:03:32,840 [input_utils.py  | 61] INFO: Get 50 orders
2023-09-24 19:03:32,840 [simulate_api.py | 87] INFO: Initial position of V_1 is e2d5093fbe36431f8986ddb0e1c586be
2023-09-24 19:03:32,841 [simulate_api.py | 87] INFO: Initial position of V_2 is 7fe14b93f0f04ee7a994ef5b2c1fdb72
2023-09-24 19:03:32,841 [simulate_api.py | 87] INFO: Initial position of V_3 is fa366fc87a124d32926daa5bb093129f
2023-09-24 19:03:32,841 [simulate_api.py | 87] INFO: Initial position of V_4 is e47399648fa842b2b8f80094343d8091
2023-09-24 19:03:32,841 [simulate_api.py | 87] INFO: Initial position of V_5 is becb4f85393540b287e7329758b8d832
2023-09-24 19:03:32,841 [simulate_environment.py | 101] INFO: **************************************************
2023-09-24 19:03:32,841 [simulate_environment.py | 105] INFO: cur time: 2023-09-24 00:10:00, pre time: 2023-09-24 00:00:00
2023-09-24 19:03:32,841 [simulate_environment.py | 187] INFO: Start to update the input of 2023-09-24 00:10:00
2023-09-24 19:03:32,843 [simulate_environment.py | 214] INFO: Get 0 unallocated order items, 0 ongoing order items, 0 completed order items
2023-09-24 19:03:32,848 [main.py         | 85] ERROR: Failed to run simulator
2023-09-24 19:03:32,849 [main.py         | 86] ERROR: Error: list index out of range, Traceback (most recent call last):
  File "/Users/wangqianlong/Desktop/personal/github/xingtian/simulator/dpdp_competition/main.py", line 80, in <module>
    score = train(Configs.factory_info_file, Configs.route_info_file, instance, agent, replay_buffer,
  File "/Users/wangqianlong/Desktop/personal/github/xingtian/simulator/dpdp_competition/src/simulator/simulate_api.py", line 125, in train
    state = agent.sar_sequence[-3]
IndexError: list index out of range

